source 'http://rubygems.org'

gem 'rails', '3.0.0'
gem "paperclip", "~> 2.3"
gem "jquery-rails"
gem "vpim"
gem 'sqlite3-ruby', :require => 'sqlite3'
gem "rails3-generators", :group => :development
gem 'bcrypt-ruby', :require => 'bcrypt'
gem "will_paginate", "~> 3.0.pre4"
gem "rake", "0.8.7"


group :test do
  gem "shoulda"
  gem 'test_notifier'
  gem 'rspec-rails', '2.6.1'
  gem 'rspec'
  gem "autotest"
  gem "factory_girl_rails"
  gem "win32console"
  gem "database_cleaner"
  gem "cucumber-rails"
  gem "cucumber"
  gem "spork"
  gem "launchy"
end
