source 'http://rubygems.org'

gem 'rails', '3.0.0'
gem "paperclip", "~> 2.3"
gem "jquery-rails"
gem "vpim"
gem 'sqlite3-ruby', :require => 'sqlite3'
gem "rails3-generators", :group => :development
gem 'bcrypt-ruby', :require => 'bcrypt'
gem "will_paginate", "~> 3.0.pre4"

group :test do
  gem "shoulda"
  gem "rspec-rails", "2.0.0"
  gem "autotest"
  gem 'webrat', '0.7.1'
  gem "factory_girl_rails"
  gem "win32console"
end
